In [ ]:
import tensorflow as tf
import numpy as np

# Task 1.1: Create a TensorFlow tensor with random float values and compute sum, mean, max
tensor = tf.random.uniform(shape=(5, 5), minval=1, maxval=20, dtype=tf.float32)
sum_tensor = tf.reduce_sum(tensor)
mean_tensor = tf.reduce_mean(tensor)
max_tensor = tf.reduce_max(tensor)

print("Tensor:", tensor.numpy())
print("Sum:", sum_tensor.numpy())
print("Mean:", mean_tensor.numpy())
print("Max:", max_tensor.numpy())

# Task 1.2: Create a 3D TensorFlow tensor and access specific elements
tensor_3d = tf.random.uniform(shape=(3, 3, 3), minval=1, maxval=20, dtype=tf.float32)
print("3D Tensor:", tensor_3d.numpy())
print("Specific Element (1,1,1):", tensor_3d.numpy()[1, 1, 1])
print("2D Slice:", tensor_3d.numpy()[1, :, :])
print("1D Slice:", tensor_3d.numpy()[1, 1, :])

Tensor: [[ 9.247681   1.8706456 18.105057   8.396138  11.45101  ]
 [16.947342  15.848382  18.719984   7.328684  11.448613 ]
 [17.26648    3.1537142  7.258832  16.786196  13.909014 ]
 [ 6.062689   2.1527667 14.045347   8.45727   12.795698 ]
 [12.290527  18.275225   7.926074  19.677822  18.503042 ]]
Sum: 297.92426
Mean: 11.91697
Max: 19.677822
3D Tensor: [[[12.717478   9.4507475  8.395277 ]
  [ 6.2855515 10.429748  19.383698 ]
  [13.286725   4.872589  17.02681  ]]

 [[ 2.1010027 19.98514   15.350741 ]
  [ 8.380186  19.285057   6.12648  ]
  [ 3.247065   1.8579595 13.500707 ]]

 [[13.325823   9.756042  18.78207  ]
  [ 1.2866532  9.406218   2.566707 ]
  [15.630391   3.2925322 12.555785 ]]]
Specific Element (1,1,1): 19.285057
2D Slice: [[ 2.1010027 19.98514   15.350741 ]
 [ 8.380186  19.285057   6.12648  ]
 [ 3.247065   1.8579595 13.500707 ]]
1D Slice: [ 8.380186 19.285057  6.12648 ]


In [ ]:
# Task 2: Function for tensor operations
def tensor_operations(tensor1, tensor2):
    tensor1 = tf.constant(tensor1, dtype=tf.float32)
    tensor2 = tf.constant(tensor2, dtype=tf.float32)
    return {
        "addition": tf.add(tensor1, tensor2).numpy(),
        "subtraction": tf.subtract(tensor1, tensor2).numpy(),
        "multiplication": tf.multiply(tensor1, tensor2).numpy(),
        "division": tf.divide(tensor1, tensor2).numpy()
    }

tensor1 = [15, 25, 35]
tensor2 = [6, 12, 18]
result = tensor_operations(tensor1, tensor2)

print("Addition:\n", result["addition"])
print("Subtraction:\n", result["subtraction"])
print("Multiplication:\n", result["multiplication"])
print("Division:\n", result["division"])


Addition:
 [21. 37. 53.]
Subtraction:
 [ 9. 13. 17.]
Multiplication:
 [ 90. 300. 630.]
Division:
 [2.5       2.0833333 1.9444444]


In [ ]:
# Task 3.1: Create a NumPy array, sort in ascending and descending order
array = np.random.rand(10) * 100
ascending_sorted = np.sort(array)
descending_sorted = np.sort(array)[::-1]
print("Original Array:", array)
print("Ascending Sorted:", ascending_sorted)
print("Descending Sorted:", descending_sorted)

# Task 3.2: Create a 2x2 NumPy matrix, compute transpose and inverse
matrix = np.random.rand(2, 2) * 50
transpose = np.transpose(matrix)
inverse = np.linalg.inv(matrix)
print("Matrix:", matrix)
print("Transpose:", transpose)
print("Inverse:", inverse)

# Task 3.3: Create a 2D NumPy array, compute row sum, column mean, and standard deviation
matrix_2d = np.random.rand(3, 3) * 10
row_sums = np.sum(matrix_2d, axis=1)
column_means = np.mean(matrix_2d, axis=0)
std_dev = np.std(matrix_2d)
print("2D Array:", matrix_2d)
print("Row Sums:", row_sums)
print("Column Means:", column_means)
print("Standard Deviation:", std_dev)

Original Array: [65.04720208 12.49195295 34.85919308 68.75630517 78.00278438 60.33716736
 66.28003707 32.9695672  49.6133579  64.15653081]
Ascending Sorted: [12.49195295 32.9695672  34.85919308 49.6133579  60.33716736 64.15653081
 65.04720208 66.28003707 68.75630517 78.00278438]
Descending Sorted: [78.00278438 68.75630517 66.28003707 65.04720208 64.15653081 60.33716736
 49.6133579  34.85919308 32.9695672  12.49195295]
Matrix: [[48.86086609  6.2069003 ]
 [32.78945274 41.06981965]]
Transpose: [[48.86086609 32.78945274]
 [ 6.2069003  41.06981965]]
Inverse: [[ 0.02277625 -0.00344219]
 [-0.01818418  0.02709696]]
2D Array: [[4.5970664  2.82196524 9.4881169 ]
 [0.57471179 1.67026823 4.01872887]
 [1.92126779 5.92456254 7.65187901]]
Row Sums: [16.90714854  6.26370888 15.49770934]
Column Means: [2.36434866 3.47226534 7.05290826]
Standard Deviation: 2.780773684637187
